# This file disables Nixpacks and forces Docker build
# Railway will use our Dockerfile instead of auto-detection

[variables]
NODE_VERSION = "20"
PYTHON_VERSION = "3.9"

# Disable Nixpacks - use Dockerfile instead
[build]
dockerfile = "./Dockerfile"

[start]
cmd = "npm start" 